version: '3.8'

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: miusuario
      POSTGRES_PASSWORD: miclave
      POSTGRES_DB: miapp
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    build: .
    restart: always
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgres://miusuario:miclave@db:5432/miapp
      SESSION_SECRET: un_secreto_seguro
      GOOGLE_CLIENT_ID: tu_google_client_id
      GOOGLE_CLIENT_SECRET: tu_google_client_secret
      CORREO_FROM: tu_email@gmail.com
      CORREO_PASS: tu_contraseña_email
    depends_on:
      - db
    volumes:
      - .:/app
    command: npm start

volumes:
  pgdata:
